import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { Plus, ChevronDown, ChevronUp } from 'lucide-react'
import { apiGet, apiPost } from '../lib/api'
import { Button } from '../components/ui/Button'
import { Input } from '../components/ui/Input'
import { Select } from '../components/ui/Select'
import { formatAed } from '../lib/utils'
import type { Driver, Salary, SalaryType } from '../types'

const SALARY_TYPE_LABELS: Record<SalaryType, string> = {
  commission: 'Commission',
  target_high: 'Target High',
  target_low: 'Target Low',
}

function currentMonth() { return new Date().toISOString().slice(0, 7) }

const schema = z.object({
  driver_id: z.string().uuid('Select a driver'),
  period_month: z.string().regex(/^\d{4}-\d{2}$/, 'YYYY-MM'),
  salary_type: z.enum(['commission', 'target_high', 'target_low']),
  total_earnings_aed: z.coerce.number().min(0),
  total_cash_received_aed: z.coerce.number().min(0),
  total_cash_submit_aed: z.coerce.number().optional(),
  cash_not_handover_aed: z.coerce.number().min(0).default(0),
  car_charging_aed: z.coerce.number().min(0).default(0),
  car_charging_used_aed: z.coerce.number().optional(),
  salik_used_aed: z.coerce.number().min(0).default(0),
  salik_refund_aed: z.coerce.number().min(0).default(0),
  rta_fine_aed: z.coerce.number().min(0).default(0),
  card_service_charges_aed: z.coerce.number().min(0).default(0),
  room_rent_aed: z.coerce.number().optional(),
})
type Form = z.infer<typeof schema>

function SalaryRow({ s }: { s: Salary }) {
  const [open, setOpen] = useState(false)

  return (
    <div className="bg-white border border-border rounded-xl overflow-hidden">
      <button
        className="w-full px-4 py-3 flex items-center justify-between text-left hover:bg-gray-50 transition-colors"
        onClick={() => setOpen((v) => !v)}
      >
        <div className="flex items-center gap-4">
          <div>
            <p className="font-semibold text-gray-900">{s.driver_name}</p>
            <p className="text-xs text-gray-500">{s.period_month} · {SALARY_TYPE_LABELS[s.salary_type_snapshot]}</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <p className="text-base font-bold text-gray-900">{formatAed(s.net_payable_aed)}</p>
          {open ? <ChevronUp className="w-4 h-4 text-gray-400" /> : <ChevronDown className="w-4 h-4 text-gray-400" />}
        </div>
      </button>

      {open && (
        <div className="px-4 pb-4 border-t border-border grid grid-cols-2 md:grid-cols-3 gap-3 pt-3 text-sm">
          <Row label="Total Earnings" value={formatAed(s.total_earnings_aed)} />
          {s.commission_aed && <Row label="Commission" value={formatAed(s.commission_aed)} />}
          {s.target_amount_aed && <Row label="Target" value={formatAed(s.target_amount_aed)} />}
          <Row label="Base Amount" value={formatAed(s.base_amount_aed)} />
          <Row label="Salik" value={formatAed(s.salik_aed)} />
          <Row label="RTA Fine" value={formatAed(s.rta_fine_aed)} />
          <Row label="Card Charges" value={formatAed(s.card_service_charges_aed)} />
          {s.room_rent_aed && <Row label="Room Rent" value={formatAed(s.room_rent_aed)} />}
          {s.car_charging_diff_aed && <Row label="Car Charging Diff" value={formatAed(s.car_charging_diff_aed)} />}
          {s.cash_not_handover_aed !== '0.00' && <Row label="Cash Not Handover" value={formatAed(s.cash_not_handover_aed)} />}
          <Row label="Final Salary" value={formatAed(s.final_salary_aed)} highlight />
          <Row label="Advance Deduction" value={formatAed(s.advance_deduction_aed)} />
          <Row label="Net Payable" value={formatAed(s.net_payable_aed)} highlight />
          <div className="col-span-2 md:col-span-3 text-xs text-gray-400 mt-1">
            Generated by {s.generated_by_name} on {new Date(s.generated_at).toLocaleDateString('en-GB')}
          </div>
        </div>
      )}
    </div>
  )
}

function Row({ label, value, highlight }: { label: string; value: string; highlight?: boolean }) {
  return (
    <div className={`rounded-lg p-2 ${highlight ? 'bg-brand/5 border border-brand/20' : 'bg-gray-50'}`}>
      <p className="text-xs text-gray-500">{label}</p>
      <p className={`font-semibold ${highlight ? 'text-brand' : 'text-gray-900'}`}>{value}</p>
    </div>
  )
}

export default function SalaryPage() {
  const qc = useQueryClient()
  const [showForm, setShowForm] = useState(false)
  const [filterDriver, setFilterDriver] = useState('')
  const [filterMonth, setFilterMonth] = useState('')

  const { data: drivers = [] } = useQuery<Driver[]>({
    queryKey: ['drivers'],
    queryFn: () => apiGet('/drivers'),
  })

  const { data: salaries = [], isLoading } = useQuery<Salary[]>({
    queryKey: ['salaries', filterDriver, filterMonth],
    queryFn: () => {
      const params = new URLSearchParams()
      if (filterDriver) params.set('driver_id', filterDriver)
      if (filterMonth) params.set('month', filterMonth)
      return apiGet(`/salaries?${params}`)
    },
  })

  const { register, handleSubmit, control, watch, reset, formState: { errors } } = useForm<Form>({
    resolver: zodResolver(schema),
    defaultValues: {
      period_month: currentMonth(),
      salary_type: 'commission',
      total_earnings_aed: 0,
      total_cash_received_aed: 0,
      cash_not_handover_aed: 0,
      car_charging_aed: 0,
      salik_used_aed: 0,
      salik_refund_aed: 0,
      rta_fine_aed: 0,
      card_service_charges_aed: 0,
    },
  })

  const salaryType = watch('salary_type')

  const { mutate, isPending, error } = useMutation({
    mutationFn: (data: Form) => apiPost('/salaries/generate', data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['salaries'] })
      reset()
      setShowForm(false)
    },
  })

  const activeDrivers = drivers.filter((d) => d.is_active)

  return (
    <div className="p-6 space-y-6 max-w-5xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Salary</h1>
          <p className="text-gray-500">Generate and view driver salary slips</p>
        </div>
        <Button onClick={() => setShowForm((v) => !v)}>
          <Plus className="w-4 h-4 mr-2" /> Generate
        </Button>
      </div>

      {/* Generate form */}
      {showForm && (
        <form
          onSubmit={handleSubmit((d) => mutate(d))}
          className="bg-white border border-border rounded-2xl p-5 space-y-4"
        >
          <h2 className="font-semibold text-gray-900">Generate Salary</h2>
          {error && (
            <p className="text-xs text-red-600 bg-red-50 rounded p-2">{(error as Error).message}</p>
          )}

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs text-gray-500 mb-1">Driver</label>
              <Controller
                name="driver_id"
                control={control}
                render={({ field }) => (
                  <Select {...field}>
                    <option value="">Select driver…</option>
                    {activeDrivers.map((d) => (
                      <option key={d.id} value={d.id}>{d.full_name}</option>
                    ))}
                  </Select>
                )}
              />
              {errors.driver_id && <p className="text-xs text-red-500 mt-1">{errors.driver_id.message}</p>}
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Month</label>
              <Input type="month" {...register('period_month')} />
            </div>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Salary Type</label>
              <Select {...register('salary_type')}>
                <option value="commission">Commission</option>
                <option value="target_high">Target High</option>
                <option value="target_low">Target Low</option>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <NumField label="Total Earnings (AED)" name="total_earnings_aed" register={register} errors={errors} />
            <NumField label="Cash Received (AED)" name="total_cash_received_aed" register={register} errors={errors} />
            <NumField label="Cash Submitted (AED)" name="total_cash_submit_aed" register={register} errors={errors} optional />
            <NumField label="Cash Not Handover (AED)" name="cash_not_handover_aed" register={register} errors={errors} />
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <NumField label="Salik Used (AED)" name="salik_used_aed" register={register} errors={errors} />
            <NumField label="Salik Refund (AED)" name="salik_refund_aed" register={register} errors={errors} />
            <NumField label="RTA Fine (AED)" name="rta_fine_aed" register={register} errors={errors} />
            <NumField label="Card Charges (AED)" name="card_service_charges_aed" register={register} errors={errors} />
          </div>

          {(salaryType === 'target_high' || salaryType === 'target_low') && (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              <NumField label="Car Charging Budget (AED)" name="car_charging_aed" register={register} errors={errors} />
              <NumField label="Car Charging Used (AED)" name="car_charging_used_aed" register={register} errors={errors} optional />
            </div>
          )}

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <NumField label="Room Rent (AED)" name="room_rent_aed" register={register} errors={errors} optional />
          </div>

          <div className="flex gap-2 justify-end">
            <Button variant="outline" type="button" onClick={() => setShowForm(false)}>Cancel</Button>
            <Button type="submit" disabled={isPending}>{isPending ? 'Generating…' : 'Generate Salary'}</Button>
          </div>
        </form>
      )}

      {/* Filters */}
      <div className="flex gap-3">
        <Select value={filterDriver} onChange={(e) => setFilterDriver(e.target.value)} className="max-w-xs">
          <option value="">All Drivers</option>
          {drivers.map((d) => (
            <option key={d.id} value={d.id}>{d.full_name}</option>
          ))}
        </Select>
        <Input
          type="month"
          value={filterMonth}
          onChange={(e) => setFilterMonth(e.target.value)}
          className="max-w-[200px]"
        />
      </div>

      {/* Salary list */}
      {isLoading ? (
        <div className="py-16 flex justify-center">
          <div className="animate-spin w-6 h-6 border-2 border-brand border-t-transparent rounded-full" />
        </div>
      ) : salaries.length === 0 ? (
        <div className="py-16 text-center text-gray-400">No salary records found</div>
      ) : (
        <div className="space-y-3">
          {salaries.map((s) => <SalaryRow key={s.id} s={s} />)}
        </div>
      )}
    </div>
  )
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function NumField({ label, name, register, errors, optional }: { label: string; name: string; register: any; errors: any; optional?: boolean }) {
  return (
    <div>
      <label className="block text-xs text-gray-500 mb-1">{label}{optional ? '' : ''}</label>
      <Input type="number" step="0.01" min="0" {...register(name)} />
      {errors[name] && <p className="text-xs text-red-500 mt-1">{errors[name].message}</p>}
    </div>
  )
}
